# need to install pyttsx3
import pyttsx3

#intialize the text to speech engine
# engine = pyttsx3.init()
engine = pyttsx3.init(driverName='nsss')


#the text you want to convert to speech
text = "Hello , I am monu siddiki from surkhet , studying Bsc.CSIT in Texas International College and this audio is generated by the python code !! "

#set properties before adding to speak
engine.setProperty('rate',100)  #speed percent(can goover 100)
engine.setProperty('volume',2.0)

#addd text to queue
engine.say(text)

#wait for the speaking to finish
engine.runAndWait()
